### ISSUE TITLE
gpg: invalid armor header

### ISSUE THREAD

**Issue by simonbcn** [openSUSE/opi#118]
```
openSUSE Tumbleweed
opi version 2.10.0
```

```
$ sudo opi chrome                                                                                                            18:03:49
Do you want to install Chrome from Google repository? (Y/n)
Which version do you want to install?
1. google-chrome-stable
2. google-chrome-beta
3. google-chrome-unstable
Pick a number (0 to quit): 1
gpg: invalid armor header: mQINBFcMjNMBEAC6Wr5QuLIFgz1V1EFPlg8ty2TsjQEl4VWftUAqWlMevJFWvYEx\n
gpg: CRC error; 84C970 - 8A5056
gpg: [don't know]: invalid packet (ctb=70)
gpg: read_block: read error: Invalid packet
gpg: import from '-' failed: Invalid keyring
Traceback (most recent call last):
File "/usr/bin/opi", line 65, in <module>
pm.run(args.query[0])
File "/usr/lib/python3.10/site-packages/opi/plugins/__init__.py", line 35, in run
plugin.run(query)
File "/usr/lib/python3.10/site-packages/opi/plugins/chrome.py", line 22, in run
opi.add_repo(
File "/usr/lib/python3.10/site-packages/opi/__init__.py", line 151, in add_repo
ask_import_key(gpgkey)
File "/usr/lib/python3.10/site-packages/opi/__init__.py", line 448, in ask_import_key
for line in subprocess.check_output(["gpg", "--quiet", "--show-keys", "--with-colons", "-"], input=key.encode()).decode().strip().split("\n"):
File "/usr/lib64/python3.10/subprocess.py", line 421, in check_output
return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
File "/usr/lib64/python3.10/subprocess.py", line 526, in run
raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['gpg', '--quiet', '--show-keys', '--with-colons', '-']' returned non-zero exit status 2.
```

**Comment by asdil12** [comment]
https://build.opensuse.org/request/show/1062072
https://build.opensuse.org/request/show/1062074
