### ISSUE TITLE
opi is broken again under Leap 15.5

### ISSUE THREAD

**Issue by ecsgh** [openSUSE/opi#163]
The problem that was fixed in 3.4.0 is now back.

**Error:**
You have selected package name: MozillaFirefox
Traceback (most recent call last):
  File "/usr/bin/opi", line 145, in <module>
    repo_query(args.query)
  File "/usr/bin/opi", line 85, in repo_query
    binaries = opi.search_local_repos(selected_name) + binaries
  File "/usr/lib/python3.6/site-packages/opi/__init__.py", line 185, in search_local_repos
    installable['repository'] = repos_by_name[repo_name]
KeyError: 'update-sle (15.5)'

**zypper lr -u:**
repositories_mozilla               | repositories:mozilla 15.5             | Ja      | (r ) Ja   | Ja      | https://download.opensuse.org/repositories/mozilla/openSUSE_Leap_15.5/

**Content of repofile:**
[repositories_mozilla]
name=repositories:mozilla $releasever
enabled=1
autorefresh=1
baseurl=https://download.opensuse.org/repositories/mozilla/openSUSE_Leap_$releasever/
path=/
type=rpm-md
keeppackages=0

**Comment by asdil12** [comment]
Could you send me the content of your `update-sle (15.5)` repo file?

**Comment by ecsgh** [comment]
Thank you.
Everything works again. :-)
