### ISSUE TITLE
opi - connection refused  - another exception occurred 

### ISSUE THREAD

**Issue by marcoczen** [openSUSE/opi#177]
Guys, is OPI broken ?

I tried it today. This is what  i got ?

```

opi apache2
    Searching repos for: apache2
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
        (self._dns_host, self.port), self.timeout, **extra_kw
      File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
        raise err
      File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
        sock.connect(sa)
    ConnectionRefusedError: [Errno 111] Connection refused

    During handling of the above exception, another exception occurred:
```

Any workarounds ?

**Comment by nobkd** [comment]
Sorry. I can't reproduce that.

Do you maybe have some software / proxy / ... interfering?
Can you share OS / system / OPI version details?

**Comment by marcoczen** [comment]
The full error message;

```
# opi apache2
Searching repos for: apache2
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 678, in urlopen
    chunked=chunked,
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 983, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 309, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f7a5a3c53c8>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 728, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='opi-proxy.opensuse.org', port=443): Max retries exceeded with url: /?obs_api_link=https%3A%2F%2Fapi.opensuse.org%2Fsearch%2Fpublished%2Fbinary%2Fid%3Fmatch%3Dcontains-ic%2528%2540name%252C%2B%2527apache2%2527%2529%2Band%2Bpath%252Fproject%253D%2527openSUSE%253ALeap%253A15.5%2527%26limit%3D0&obs_instance=openSUSE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7a5a3c53c8>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/opi", line 146, in <module>
    repo_query(args.query)
  File "/usr/bin/opi", line 72, in repo_query
    packages.extend(opi.search_published_packages('openSUSE', query))
  File "/usr/lib/python3.6/site-packages/opi/__init__.py", line 500, in search_published_packages
    r = requests.get(PROXY_URL, params={'obs_api_link': url, 'obs_instance': obs_instance})
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='opi-proxy.opensuse.org', port=443): Max retries exceeded with url: /?obs_api_link=https%3A%2F%2Fapi.opensuse.org%2Fsearch%2Fpublished%2Fbinary%2Fid%3Fmatch%3Dcontains-ic%2528%2540name%252C%2B%2527apache2%2527%2529%2Band%2Bpath%252Fproject%253D%2527openSUSE%253ALeap%253A15.5%2527%26limit%3D0&obs_instance=openSUSE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7a5a3c53c8>: Failed to establish a new connection: [Errno 111] Connection refused',))


```

**Comment by asdil12** [comment]
What does `curl -v https://opi-proxy.opensuse.org/` output?
If you can reach it, it should return something like this:

```
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>The browser (or proxy) sent a request that this server could not understand.</p>
```

So your filewall would need to allow https connections on port 443 to opi-proxy.opensuse.org

**Comment by marcoczen** [comment]
> If you can reach it, it should return something like this:

Hi ... As below;

``` 
# nc -v opi-proxy.opensuse.org 443
nc: connect to opi-proxy.opensuse.org port 443 (tcp) failed: Connection refused
nc: connect to opi-proxy.opensuse.org port 443 (tcp) failed: Network is unreachable

# nc -v download.opensuse.org 443
Connection to download.opensuse.org 443 port [tcp/https] succeeded!

# nc -v google.com 443
Connection to google.com 443 port [tcp/https] succeeded!

```

**Comment by asdil12** [comment]
Port 443 on opi-proxy.opensuse.org needs to be allowed, but that doesn't seem to work from your system.

It works for me, though. Both via IPv4 and IPv6.

**Comment by marcoczen** [comment]
Hi. I uninstalled and reinstalled opi. It doesnt show any errors now.

I ran ```opi apache2``` and got a list of output. I havent figured out how to make it show info about each package and how to install though.

**Comment by asdil12** [comment]
just select the number of the entry you want as shown here:

![image](https://github.com/openSUSE/opi/assets/725608/47ccc433-5f68-4719-aa07-ff49b6caaebf)

**Comment by marcoczen** [comment]
Ok. Looks like  I didnt get the lower portion of the output - back to the drawing board for me then ....

**Comment by marcoczen** [comment]
Closed
