### ISSUE TITLE
Exit status 106 after picking a package

### ISSUE THREAD

**Issue by DrDoctor13** [openSUSE/opi#179]
Using Filezilla as an example:

```
archie@localhost:~> opi filezilla
Searching repos for: filezilla
 1. filezilla
 2. libfilezilla43
 3. libfilezilla42
 4. libfilezilla36
 5. filezilla-lang
 6. filezilla-devel
 7. filezilla-server
 8. libfilezilla-lang
 9. libfilezilla-devel
10. filezilla-debuginfo
11. filezilla-debugsource
12. filezilla-server-gui
13. libfilezilla-debugsource
14. libfilezilla43-debuginfo
15. filezilla-server-debuginfo
16. filezilla-server-debugsource
17. filezilla-server-gui-debuginfo
Pick a number (0 to quit): 1
You have selected package name: filezilla
Some of the repositories had to be skipped due to missing metadata.
Traceback (most recent call last):
  File "/usr/bin/opi", line 146, in <module>
    repo_query(args.query)
  File "/usr/bin/opi", line 85, in repo_query
    packages = opi.search_local_repos(selected_pkg_name) + packages
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/opi/__init__.py", line 206, in search_local_repos
    sr = subprocess.check_output(['zypper', '-ntc', zc.name, '--no-refresh', 'se', '-sx', '-tpackage', package], env={'LANG': 'c'}).decode()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['zypper', '-ntc', '/tmp/tmpkua929uq', '--no-refresh', 'se', '-sx', '-tpackage', 'filezilla']' returned non-zero exit status 106.
```

Tested on Tumbleweed 20240505

**Comment by asdil12** [comment]
Can you send me your output of `zypper lr -u`?
> Some of the repositories had to be skipped due to missing metadata.

It seems that you maybe have some bad repos added.

**Comment by DrDoctor13** [comment]
```
archie@localhost:~> zypper lr -u
Repository priorities in effect:                                              (See 'zypper lr -P' for details)
      90 (raised priority)  :  1 repository
      99 (default priority) :  4 repositories

# | Alias                            | Name                                   | Enabled | GPG Check | Refresh | URI
--+----------------------------------+----------------------------------------+---------+-----------+---------+----------------------------------------------------------
1 | download.opensuse.org-non-oss    | Main Repository (NON-OSS)              | Yes     | ( p) Yes  | Yes     | http://download.opensuse.org/tumbleweed/repo/non-oss/
2 | download.opensuse.org-oss        | Main Repository (OSS)                  | Yes     | ( p) Yes  | Yes     | http://download.opensuse.org/tumbleweed/repo/oss/
3 | download.opensuse.org-tumbleweed | Main Update Repository                 | Yes     | ( p) Yes  | Yes     | http://download.opensuse.org/update/tumbleweed/
4 | openSUSE-20240414-0              | openSUSE-20240414-0                    | No      | ----      | ----    | cd:/?devices=/dev/disk/by-id/ata-VBOX_CD-ROM_VB2-01700376
5 | packman                          | Packman                                | Yes     | ( p) Yes  | Yes     | https://ftp.fau.de/packman//suse/openSUSE_Tumbleweed/
6 | repo-debug                       | openSUSE-Tumbleweed-Debug              | No      | ----      | ----    | http://download.opensuse.org/debug/tumbleweed/repo/oss/
7 | repo-openh264                    | Open H.264 Codec (openSUSE Tumbleweed) | Yes     | (r ) Yes  | Yes     | http://codecs.opensuse.org/openh264/openSUSE_Tumbleweed
8 | repo-source                      | openSUSE-Tumbleweed-Source             | No      | ----      | ----    | http://download.opensuse.org/source/tumbleweed/repo/oss/

```

**Comment by asdil12** [comment]
hm - that actually looks fine - could you run `zypper ref` for me?

**Comment by DrDoctor13** [comment]
Everything looks fine.

```
archie@localhost:~> sudo zypper ref
[sudo] password for root: 
Repository 'Main Repository (NON-OSS)' is up to date.                                                         
Repository 'Main Repository (OSS)' is up to date.                                                             
Repository 'Main Update Repository' is up to date.                                                            
Repository 'Packman' is up to date.                                                                           
Repository 'Open H.264 Codec (openSUSE Tumbleweed)' is up to date.                                            
All repositories have been refreshed.
```

**Comment by asdil12** [comment]
So is the issue still appearing?

If yes, please send me the output of:
```
echo -e "[main]\nshowAlias = true\n" > /tmp/zc
zypper -ntc /tmp/zc --no-refresh se -sx -tpackage filezilla
```

**Comment by DrDoctor13** [comment]
```
archie@localhost:~> echo -e "[main]\nshowAlias = true\n" > /tmp/zc
archie@localhost:~> zypper -ntc /tmp/zc --no-refresh se -sx -tpackage filezilla
Repository                       : Time since last refresh
download.opensuse.org-non-oss    : No permission to read metadata! Skipping it!
download.opensuse.org-oss        : No permission to read metadata! Skipping it!
download.opensuse.org-tumbleweed : No permission to read metadata! Skipping it!
packman                          : No permission to read metadata! Skipping it!
repo-openh264                    : 1 min 7 s 

Some of the repositories had to be skipped due to missing metadata.

    Note: Running with user privileges. From time to time run 'zypper refresh' as root to make sure
    the repository metadata are complete and up-to-date.

Loading repository data...
Reading installed packages...
No matching items found.
```
Looks like this is on me then. For some reason, I didn't think you had to run `opi` with sudo. Running the above command with sudo outputs:
```
archie@localhost:~> sudo zypper -ntc /tmp/zc --no-refresh se -sx -tpackage filezilla
[sudo] password for root: 
Loading repository data...
Reading installed packages...

S | Name      | Type    | Version    | Arch   | Repository
--+-----------+---------+------------+--------+--------------------------
  | filezilla | package | 3.67.0-2.1 | x86_64 | download.opensuse.org-oss
```
And when running `sudo opi filezilla`...
```
archie@localhost:~> sudo opi filezilla
Searching repos for: filezilla
 1. filezilla
 2. libfilezilla43
 3. libfilezilla42
 4. libfilezilla36
 5. filezilla-lang
 6. filezilla-devel
 7. filezilla-server
 8. libfilezilla-lang
 9. libfilezilla-devel
10. filezilla-debuginfo
11. filezilla-debugsource
12. filezilla-server-gui
13. libfilezilla-debugsource
14. libfilezilla43-debuginfo
15. filezilla-server-debuginfo
16. filezilla-server-debugsource
17. filezilla-server-gui-debuginfo
Pick a number (0 to quit): 1
You have selected package name: filezilla
1. Main Repository (OSS) +                   | 3.67.0                    | x86_64
2. openSUSE:Factory -                        | 3.67.0                    | x86_64
3. network ?                                 | 3.67.0                    | x86_64
4. home:aschnell:boost !                     | 3.67.0                    | x86_64
5. home:ecsos !                              | 3.67.0                    | x86_64
6. home:ecsos:test2 !                        | 3.67.0                    | x86_64
7. home:simotek:base !                       | 3.67.0                    | x86_64
8. home:alucardx:filezilla !                 | 3.66.5                    | x86_64

```

**Comment by asdil12** [comment]
Actually you shouldn't have to run it as root. It should sudo automatically when needed.
And this zypper command houldn't need root.

For some reason it can't read the repo metadata - even though it should be able to.

It looks like there is something wrong with the permissions of your repo metadata cache.
Could you send me the output of `ls -lR /var/cache/zypp`?

**Comment by DrDoctor13** [comment]
I did accidentally update to 20240512 and opi appears to be behaving normally now. No idea what happened. For what it's worth, here is the output:
```
archie@localhost:~> ls -lR /var/cache/zypp
/var/cache/zypp:
total 0
drwxr-xr-x 1 root root  42 May 14 23:11 geoip.d
drwxr-xr-x 1 root root 186 Apr 28 10:08 packages
drwxr-xr-x 1 root root 250 May 14 23:13 raw
drwxr-xr-x 1 root root 264 May 14 23:11 solv

/var/cache/zypp/geoip.d:
total 4
-rw-r--r-- 1 root root 17 May 14 23:11 download.opensuse.org

/var/cache/zypp/packages:
total 0
drwxr-xr-x 1 root root 12 Apr 28 10:08 download.opensuse.org-non-oss
drwxr-xr-x 1 root root 24 Apr 16 00:42 download.opensuse.org-oss
drwxr-xr-x 1 root root 24 Apr 16 00:37 openSUSE-20240414-0
drwxr-xr-x 1 root root 40 Apr 16 01:07 packman
drwxr-xr-x 1 root root 12 Apr 16 01:08 repo-openh264

/var/cache/zypp/packages/download.opensuse.org-non-oss:
total 0
drwxr-xr-x 1 root root 0 Apr 28 10:14 noarch

/var/cache/zypp/packages/download.opensuse.org-non-oss/noarch:
total 0

/var/cache/zypp/packages/download.opensuse.org-oss:
total 0
drwxr-xr-x 1 root root 0 May 13 21:59 noarch
drwxr-xr-x 1 root root 0 May 13 22:00 x86_64

/var/cache/zypp/packages/download.opensuse.org-oss/noarch:
total 0

/var/cache/zypp/packages/download.opensuse.org-oss/x86_64:
total 0

/var/cache/zypp/packages/openSUSE-20240414-0:
total 0
drwxr-xr-x 1 root root 0 Apr 16 00:54 noarch
drwxr-xr-x 1 root root 0 Apr 16 00:37 x86_64

/var/cache/zypp/packages/openSUSE-20240414-0/noarch:
total 0

/var/cache/zypp/packages/openSUSE-20240414-0/x86_64:
total 0

/var/cache/zypp/packages/packman:
total 0
drwxr-xr-x 1 root root 24 Apr 16 01:07 Essentials
drwxr-xr-x 1 root root 12 Apr 16 01:07 Multimedia

/var/cache/zypp/packages/packman/Essentials:
total 0
drwxr-xr-x 1 root root 0 May 13 21:59 noarch
drwxr-xr-x 1 root root 0 May 13 22:00 x86_64

/var/cache/zypp/packages/packman/Essentials/noarch:
total 0

/var/cache/zypp/packages/packman/Essentials/x86_64:
total 0

/var/cache/zypp/packages/packman/Multimedia:
total 0
drwxr-xr-x 1 root root 0 Apr 28 09:38 x86_64

/var/cache/zypp/packages/packman/Multimedia/x86_64:
total 0

/var/cache/zypp/packages/repo-openh264:
total 0
drwxr-xr-x 1 root root 0 Apr 16 01:08 x86_64

/var/cache/zypp/packages/repo-openh264/x86_64:
total 0

/var/cache/zypp/raw:
total 0
drwx------ 1 root root 58 May 13 21:42 download.opensuse.org-non-oss
drwx------ 1 root root 58 May 13 21:42 download.opensuse.org-oss
drwx------ 1 root root 44 Apr 16 00:37 download.opensuse.org-tumbleweed
drwx------ 1 root root 58 Apr 16 00:37 openSUSE-20240414-0
drwx------ 1 root root 44 May 14 23:11 packman
drwxr-xr-x 1 root root 44 Apr 16 00:55 repo-openh264
ls: cannot open directory '/var/cache/zypp/raw/download.opensuse.org-non-oss': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/download.opensuse.org-oss': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/download.opensuse.org-tumbleweed': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/openSUSE-20240414-0': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/packman': Permission denied

/var/cache/zypp/raw/repo-openh264:
total 0
drwxr-xr-x 1 root root 660 Apr 16 00:55 repodata

/var/cache/zypp/raw/repo-openh264/repodata:
total 28
-rw-r--r-- 1 root root 7750 Apr 16 00:55 7604cfd322115da24101e4de8d0628d2b844a373a8d226150669226227e693e7a653e4ad7e1e7296a8a620cc1a0a3586ea2f9c1ffeeba037f21a71abd2ed1082-primary.xml.gz
-rw-r--r-- 1 root root 4201 Apr 16 00:55 ce517417368c3f57bfe0be8291286b3641211e67937a734bf462d6c22e8de1d7b08ad654d2e368f83bbc002d331e7dd166455c0458a6c448f373b4e1e4adba6b-filelists-ext.xml.gz
-rw-r--r-- 1 root root 2957 May 14 23:13 repomd.xml
-rw-r--r-- 1 root root  827 Apr 16 00:55 repomd.xml.asc
-rw-r--r-- 1 root root 1687 Apr 16 00:55 repomd.xml.key

/var/cache/zypp/solv:
total 0
drwxr-xr-x 1 root root 36 May 13 21:42 download.opensuse.org-non-oss
drwxr-xr-x 1 root root 36 May 13 21:42 download.opensuse.org-oss
drwxr-xr-x 1 root root 36 Apr 16 00:37 download.opensuse.org-tumbleweed
drwxr-xr-x 1 root root 36 Apr 16 00:37 openSUSE-20240414-0
drwxr-xr-x 1 root root 36 May 14 23:11 packman
drwxr-xr-x 1 root root 36 Apr 16 00:55 repo-openh264
drwxr-xr-x 1 root root 36 May 13 22:00 @System

/var/cache/zypp/solv/download.opensuse.org-non-oss:
total 48
-rw-r--r-- 1 root root    52 May 13 21:42 cookie
-rw-r--r-- 1 root root 38057 May 13 21:42 solv
-rw-r--r-- 1 root root  1399 May 13 21:42 solv.idx

/var/cache/zypp/solv/download.opensuse.org-oss:
total 28812
-rw-r--r-- 1 root root       52 May 13 21:42 cookie
-rw-r--r-- 1 root root 27361386 May 13 21:42 solv
-rw-r--r-- 1 root root  2131711 May 13 21:42 solv.idx

/var/cache/zypp/solv/download.opensuse.org-tumbleweed:
total 24
-rw-r--r-- 1 root root    52 Apr 16 00:37 cookie
-rw-r--r-- 1 root root 15715 Apr 16 00:37 solv
-rw-r--r-- 1 root root  1897 Apr 16 00:37 solv.idx

/var/cache/zypp/solv/openSUSE-20240414-0:
total 4056
-rw-r--r-- 1 root root      52 Apr 16 00:37 cookie
-rw-r--r-- 1 root root 3981573 Apr 16 00:37 solv
-rw-r--r-- 1 root root  162553 Apr 16 00:37 solv.idx

/var/cache/zypp/solv/packman:
total 2648
-rw-r--r-- 1 root root      52 May 14 23:11 cookie
-rw-r--r-- 1 root root 2390808 May 14 23:11 solv
-rw-r--r-- 1 root root  313448 May 14 23:11 solv.idx

/var/cache/zypp/solv/repo-openh264:
total 24
-rw-r--r-- 1 root root    52 Apr 16 00:55 cookie
-rw-r--r-- 1 root root 12406 Apr 16 00:55 solv
-rw-r--r-- 1 root root  1823 Apr 16 00:55 solv.idx

/var/cache/zypp/solv/@System:
total 3984
-rw-r--r-- 1 root root      52 May 13 22:00 cookie
-rw-r--r-- 1 root root 3979843 May 13 22:00 solv
-rw-r--r-- 1 root root   93850 May 13 22:00 solv.idx

```

**Comment by asdil12** [comment]
You could simply delete the directories mentioned below and afterwards run `zypper ref` as root:

```
ls: cannot open directory '/var/cache/zypp/raw/download.opensuse.org-non-oss': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/download.opensuse.org-oss': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/download.opensuse.org-tumbleweed': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/openSUSE-20240414-0': Permission denied
ls: cannot open directory '/var/cache/zypp/raw/packman': Permission denied
```

**Comment by DrDoctor13** [comment]
After doing that, that command completes without error. `opi` behaves too.
```
/var/cache/zypp:
total 0
drwxr-xr-x 1 root root  42 May 14 23:11 geoip.d
drwxr-xr-x 1 root root 186 Apr 28 10:08 packages
drwxr-xr-x 1 root root 212 May 15 18:36 raw
drwxr-xr-x 1 root root 264 May 15 18:33 solv

/var/cache/zypp/geoip.d:
total 4
-rw-r--r-- 1 root root 17 May 14 23:11 download.opensuse.org

/var/cache/zypp/packages:
total 0
drwxr-xr-x 1 root root 12 Apr 28 10:08 download.opensuse.org-non-oss
drwxr-xr-x 1 root root 24 Apr 16 00:42 download.opensuse.org-oss
drwxr-xr-x 1 root root 24 Apr 16 00:37 openSUSE-20240414-0
drwxr-xr-x 1 root root 40 Apr 16 01:07 packman
drwxr-xr-x 1 root root 12 Apr 16 01:08 repo-openh264

/var/cache/zypp/packages/download.opensuse.org-non-oss:
total 0
drwxr-xr-x 1 root root 0 Apr 28 10:14 noarch

/var/cache/zypp/packages/download.opensuse.org-non-oss/noarch:
total 0

/var/cache/zypp/packages/download.opensuse.org-oss:
total 0
drwxr-xr-x 1 root root 0 May 13 21:59 noarch
drwxr-xr-x 1 root root 0 May 13 22:00 x86_64

/var/cache/zypp/packages/download.opensuse.org-oss/noarch:
total 0

/var/cache/zypp/packages/download.opensuse.org-oss/x86_64:
total 0

/var/cache/zypp/packages/openSUSE-20240414-0:
total 0
drwxr-xr-x 1 root root 0 Apr 16 00:54 noarch
drwxr-xr-x 1 root root 0 Apr 16 00:37 x86_64

/var/cache/zypp/packages/openSUSE-20240414-0/noarch:
total 0

/var/cache/zypp/packages/openSUSE-20240414-0/x86_64:
total 0

/var/cache/zypp/packages/packman:
total 0
drwxr-xr-x 1 root root 24 Apr 16 01:07 Essentials
drwxr-xr-x 1 root root 12 Apr 16 01:07 Multimedia

/var/cache/zypp/packages/packman/Essentials:
total 0
drwxr-xr-x 1 root root 0 May 13 21:59 noarch
drwxr-xr-x 1 root root 0 May 13 22:00 x86_64

/var/cache/zypp/packages/packman/Essentials/noarch:
total 0

/var/cache/zypp/packages/packman/Essentials/x86_64:
total 0

/var/cache/zypp/packages/packman/Multimedia:
total 0
drwxr-xr-x 1 root root 0 Apr 28 09:38 x86_64

/var/cache/zypp/packages/packman/Multimedia/x86_64:
total 0

/var/cache/zypp/packages/repo-openh264:
total 0
drwxr-xr-x 1 root root 0 Apr 16 01:08 x86_64

/var/cache/zypp/packages/repo-openh264/x86_64:
total 0

/var/cache/zypp/raw:
total 0
drwxr-xr-x 1 root root 58 May 15 18:36 download.opensuse.org-non-oss
drwxr-xr-x 1 root root 58 May 15 18:36 download.opensuse.org-oss
drwxr-xr-x 1 root root 44 May 15 18:36 download.opensuse.org-tumbleweed
drwxr-xr-x 1 root root 44 May 15 18:36 packman
drwxr-xr-x 1 root root 44 Apr 16 00:55 repo-openh264

/var/cache/zypp/raw/download.opensuse.org-non-oss:
total 0
drwxr-xr-x 1 root root  10 May 15 18:36 media.1
drwxr-xr-x 1 root root 852 May 15 18:36 repodata

/var/cache/zypp/raw/download.opensuse.org-non-oss/media.1:
total 4
-rw-r--r-- 1 root root 109 May 15 18:36 media

/var/cache/zypp/raw/download.opensuse.org-non-oss/repodata:
total 76
-rw-r--r-- 1 root root 12692 May 15 18:36 24edaf5f1096d1f69fd90544e1bf30f123eaa4e71ffba71d18336dfdd1f75f10-appdata-icons.tar.gz
-rw-r--r-- 1 root root  2672 May 15 18:36 c912481834962c1bcff6b5df4fc17ce675e1b168e1f5bf574394433a0e1f21ac-appdata.xml.gz
-rw-r--r-- 1 root root 13563 May 15 18:36 dfe544ffec5d0230af59d0d65873a7f5d7f573260df9f01fcab65ecf588cc54c-susedata.xml.gz
-rw-r--r-- 1 root root 17014 May 15 18:36 edad4373e0e90fd215b0443f3c2a0d504a6c153fef4b7c37441e4708764d457deb1c6fd03fafaf4fdc671c204773b62737407f6ef8108ab4693308a811a8a2fc-primary.xml.zst
-rw-r--r-- 1 root root 10007 May 15 18:36 repomd.xml
-rw-r--r-- 1 root root   827 May 15 18:36 repomd.xml.asc
-rw-r--r-- 1 root root  1687 May 15 18:36 repomd.xml.key

/var/cache/zypp/raw/download.opensuse.org-oss:
total 0
drwxr-xr-x 1 root root   10 May 15 18:36 media.1
drwxr-xr-x 1 root root 1140 May 15 18:36 repodata

/var/cache/zypp/raw/download.opensuse.org-oss/media.1:
total 4
-rw-r--r-- 1 root root 93 May 15 18:36 media

/var/cache/zypp/raw/download.opensuse.org-oss/repodata:
total 34128
-rw-r--r-- 1 root root 17034726 May 15 18:36 050ff2c8b1965485afe9ef6dde787cce87783113fd9d6b6645f7d1caccb413e1b8d429a2b278b94a9d52d0c9da6d1ea06dc5480456d7f4f51dd100b4add230df-primary.xml.zst
-rw-r--r-- 1 root root    65306 May 15 18:36 06a00321035620d2e2b84d18c22921544d3487e86a232dac5ff182e379c619331df2f10bf30c31eef6580bc1e8230d4a57ff2f81b6cce7b3865bbb8936c3fb77-license.tar.zst
-rw-r--r-- 1 root root  4745042 May 15 18:36 3170987ec0966031cf27702e8bce219b2296a2dd4ff7360b41a428e2179e7252-appdata-icons.tar.gz
-rw-r--r-- 1 root root  6718016 May 15 18:36 dc3b364a3723d175f83b0bbeb75fb8a9ecaf345efd2a77cbb6144156ed348f08-appdata.xml.gz
-rw-r--r-- 1 root root  6355351 May 15 18:36 ebb561bc585fb468713bba06e58464bee2cfec846611146e664e507687fda9d6-susedata.xml.gz
-rw-r--r-- 1 root root    10729 May 15 18:36 repomd.xml
-rw-r--r-- 1 root root      827 May 15 18:36 repomd.xml.asc
-rw-r--r-- 1 root root     1687 May 15 18:36 repomd.xml.key

/var/cache/zypp/raw/download.opensuse.org-tumbleweed:
total 0
drwxr-xr-x 1 root root 952 May 15 18:36 repodata

/var/cache/zypp/raw/download.opensuse.org-tumbleweed/repodata:
total 32
-rw-r--r-- 1 root root  992 May 15 18:36 1c5cd8e33993bd592a2df5af7fc09e11c6a73270afd243b7e780927952a7b0a4d09732f2b97fb5f88cf4045be0d448eed78a91bfa6d6979aa267245d7869f8c8-updateinfo.xml.gz
-rw-r--r-- 1 root root 6646 May 15 18:36 672d69f204f96296e40329c3b054bf8dff96687aa3c00eb78d17ab27942e1b5869c59b7f8b205b2d959df426adc9147a7c6d9bd4c7fc1588100403af9c21b475-primary.xml.gz
-rw-r--r-- 1 root root 4319 May 15 18:36 7a98a5559622398c59c78c5e20ac339bb906bad8f4c22bbc4d15369204e18cfd3645d61668fcd5957b73720135aa5bf7193dd6740d21644093e58a189b5e7046-filelists-ext.xml.gz
-rw-r--r-- 1 root root 3387 May 15 18:36 repomd.xml
-rw-r--r-- 1 root root  827 May 15 18:36 repomd.xml.asc
-rw-r--r-- 1 root root 1687 May 15 18:36 repomd.xml.key

/var/cache/zypp/raw/packman:
total 0
drwxr-xr-x 1 root root 104 May 15 18:36 repodata

/var/cache/zypp/raw/packman/repodata:
total 2128
-rw-r--r-- 1 root root 2164070 May 15 18:36 primary.xml.gz
-rw-r--r-- 1 root root    1378 May 15 18:36 repomd.xml
-rw-r--r-- 1 root root     836 May 15 18:36 repomd.xml.asc
-rw-r--r-- 1 root root    1715 May 15 18:36 repomd.xml.key

/var/cache/zypp/raw/repo-openh264:
total 0
drwxr-xr-x 1 root root 660 Apr 16 00:55 repodata

/var/cache/zypp/raw/repo-openh264/repodata:
total 28
-rw-r--r-- 1 root root 7750 Apr 16 00:55 7604cfd322115da24101e4de8d0628d2b844a373a8d226150669226227e693e7a653e4ad7e1e7296a8a620cc1a0a3586ea2f9c1ffeeba037f21a71abd2ed1082-primary.xml.gz
-rw-r--r-- 1 root root 4201 Apr 16 00:55 ce517417368c3f57bfe0be8291286b3641211e67937a734bf462d6c22e8de1d7b08ad654d2e368f83bbc002d331e7dd166455c0458a6c448f373b4e1e4adba6b-filelists-ext.xml.gz
-rw-r--r-- 1 root root 2957 May 15 18:36 repomd.xml
-rw-r--r-- 1 root root  827 Apr 16 00:55 repomd.xml.asc
-rw-r--r-- 1 root root 1687 Apr 16 00:55 repomd.xml.key

/var/cache/zypp/solv:
total 0
drwxr-xr-x 1 root root 36 May 15 18:33 download.opensuse.org-non-oss
drwxr-xr-x 1 root root 36 May 15 18:33 download.opensuse.org-oss
drwxr-xr-x 1 root root 36 Apr 16 00:37 download.opensuse.org-tumbleweed
drwxr-xr-x 1 root root 36 Apr 16 00:37 openSUSE-20240414-0
drwxr-xr-x 1 root root 36 May 15 18:33 packman
drwxr-xr-x 1 root root 36 Apr 16 00:55 repo-openh264
drwxr-xr-x 1 root root 36 May 13 22:00 @System

/var/cache/zypp/solv/download.opensuse.org-non-oss:
total 48
-rw-r--r-- 1 root root    52 May 15 18:33 cookie
-rw-r--r-- 1 root root 38057 May 15 18:33 solv
-rw-r--r-- 1 root root  1399 May 15 18:33 solv.idx

/var/cache/zypp/solv/download.opensuse.org-oss:
total 28836
-rw-r--r-- 1 root root       52 May 15 18:33 cookie
-rw-r--r-- 1 root root 27386083 May 15 18:33 solv
-rw-r--r-- 1 root root  2132365 May 15 18:33 solv.idx

/var/cache/zypp/solv/download.opensuse.org-tumbleweed:
total 24
-rw-r--r-- 1 root root    52 Apr 16 00:37 cookie
-rw-r--r-- 1 root root 15715 Apr 16 00:37 solv
-rw-r--r-- 1 root root  1897 Apr 16 00:37 solv.idx

/var/cache/zypp/solv/openSUSE-20240414-0:
total 4056
-rw-r--r-- 1 root root      52 Apr 16 00:37 cookie
-rw-r--r-- 1 root root 3981573 Apr 16 00:37 solv
-rw-r--r-- 1 root root  162553 Apr 16 00:37 solv.idx

/var/cache/zypp/solv/packman:
total 2648
-rw-r--r-- 1 root root      52 May 15 18:33 cookie
-rw-r--r-- 1 root root 2391778 May 15 18:33 solv
-rw-r--r-- 1 root root  313390 May 15 18:33 solv.idx

/var/cache/zypp/solv/repo-openh264:
total 24
-rw-r--r-- 1 root root    52 Apr 16 00:55 cookie
-rw-r--r-- 1 root root 12406 Apr 16 00:55 solv
-rw-r--r-- 1 root root  1823 Apr 16 00:55 solv.idx

/var/cache/zypp/solv/@System:
total 3984
-rw-r--r-- 1 root root      52 May 13 22:00 cookie
-rw-r--r-- 1 root root 3979843 May 13 22:00 solv
-rw-r--r-- 1 root root   93850 May 13 22:00 solv.idx
```

**Comment by asdil12** [comment]
I don't know how that permissions got messed up on your system in the first place, but I guess it is fine now.
