### ISSUE TITLE
Opi fails when installing anything from software.opensuse.org

### ISSUE THREAD

**Issue by catbabylon** [openSUSE/opi#73]
I get the following error message:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fdff6c5adc0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='guoyunhe.me', port=443): Max retries exceeded with url: /opi/proxy/index.php?obs_api_link=https%3A%2F%2Fapi.opensuse.org%2Fsearch%2Fpublished%2Fbinary%2Fid%3Fmatch%3Dcontains-ic%2528%2540name%252C%2B%2527micro-editor%2527%2529%2Band%2Bpath%252Fproject%253D%2527openSUSE%253AFactory%2527%26limit%3D0&obs_instance=openSUSE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdff6c5adc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/opi", line 69, in <module>
    binaries.extend(opi.search_published_binary('openSUSE', args.query))
  File "/usr/lib/python3.8/site-packages/opi/__init__.py", line 159, in search_published_binary
    r = requests.get(PROXY_URL, params={'obs_api_link': url, 'obs_instance': obs_instance})
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='guoyunhe.me', port=443): Max retries exceeded with url: /opi/proxy/index.php?obs_api_link=https%3A%2F%2Fapi.opensuse.org%2Fsearch%2Fpublished%2Fbinary%2Fid%3Fmatch%3Dcontains-ic%2528%2540name%252C%2B%2527micro-editor%2527%2529%2Band%2Bpath%252Fproject%253D%2527openSUSE%253AFactory%2527%26limit%3D0&obs_instance=openSUSE (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fdff6c5adc0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
```

It looks like other people are reporting similar issues on Reddit.

**Comment by asdil12** [comment]
@guoyunhe can you have a look at the server?

**Comment by akagusu** [comment]
> @guoyunhe can you have a look at the server?

The last time I checked, the server was down. 
Is there some reason for the opi points to a personal server?

**Comment by asdil12** [comment]
The server seems to be online again.


> Is there some reason for the opi points to a personal server?

OPI needs some proxy server that allows certain API calls to the OBS and packman build service API.
A direct access of of the API would require authentication.
Therefore @guoyunhe set up such a proxy - and that stayed like that ever since.

I currently try to get a `*.opensuse.org` server for this, but this seems to take some time.

**Comment by DomingoMontoya** [comment]
Is there any documentation/tips on setting up a proxy server? I set one up and was unable to get it to work using the local running version from command line, or running on a dedicated server. It launched, and ran fine, but was unable to open the stream. User and pass were set for the OBS and packman API's.

It seemed very straightforward, yet failed.

**Comment by asdil12** [comment]
I wrote python version of the proxy that seems to work better than the PHP version.
It is just not completely ready to be committed but it seems to work well:

`application.py`:
```python
#!/usr/bin/python3

import json

import requests
from flask import Flask, request, Response

app = Flask(__name__)

config = json.load(open('config.json'))

@app.route('/')
def endpoint():
        c = config[request.args['obs_instance']]
        assert request.args['obs_api_link'].startswith(c['url'])
        r = requests.get(request.args['obs_api_link'], auth=(c['user'], c['pass']))
        r.raise_for_status()
        return Response(
                r.text,
                status=r.status_code,
                headers={
                        "Access-Control-Allow-Origin": "*"
                },
                mimetype=r.headers.get("content-type", "text/plain")
        )

if __name__ == '__main__':
        app.run(host='0.0.0.0', debug=True)
```

`config.json`:
```json
{
        "openSUSE": {
                "user": "OBS_USERNAME",
                "pass": "OBS_PASS",
                "url": "https://api.opensuse.org/"
        },
        "Packman": {
                "user": "PMBS_USERNAME",
                "pass": "PMBS_PASS",
                "url": "https://pmbs.links2linux.de/"
        }
}
```

Simply run in by calling `./application.py`

**Comment by asdil12** [comment]
The proxy provided by Guo is online again - in the meantime I got a machine from opensuse running.
